modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="vanillaforging"
version="1.0.0"
displayName="Vanilla Forging"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="Merciless"

[[dependencies.vanillaforging]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"



